spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        #负载均衡配置，配置中心还有另一配置
        - id: app
          uri: lb://provider-hello
          predicates:
            - Path=/test/**
# redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
#项目配置
rrs:
  sc-gateway:
    dynamicRoute:
      enabled: true
      from: nacos

